config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :new]
  resources :welcome, only: [:index]
  resources :todo_lists do
    resources :items do
      member do
        patch :complete
      end
    end
  end

  resources :photos
  resources :password_resets, only: [:new, :create,:edit, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'welcome#index'

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
  validates :title, presence: true
  validates :title, length: { minimum: 3 }

  def is_incomplete_items?
    items.incomplete.size > 0
  end

  def is_complete_items?
    items.complete.size > 0
  end



end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_user
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in? && current_user.admin?
      @todo_lists = TodoList.all
    else
      # byebug
      @todo_lists = current_user.todo_lists
    end

  end

  def show
  end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def edit
  end

  def create
    # byebug
    @todo_list = current_user.todo_lists.new(todo_list_params)
    if @todo_list.save
      # byebug
      redirect_to @todo_list, notice: 'Todo list was successfully created.'
    else
      render :new
    end
  end

  def update
    if @todo_list.update(todo_list_params)
      # byebug
      redirect_to @todo_list, notice: 'Todo list was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    # @todo_list = TodoList.find(params[:id])
    @todo_list.destroy
    redirect_to todo_lists_path , notice: 'Todo list was successfully destroyed.'
  end

end



private

def set_todo_list
  # check scope again
  @todo_list = @current_user.todo_lists.find(params[:id])
  # byebug
end

def todo_list_params
  params.require(:todo_list).permit(:title)
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
      <ul>
        <% @todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<div class="row">
  <div class="col-md-10">
    <% @todo_lists.each do |todo_list| %>
      <div class="panel panel-success">
        <div class="panel-heading">
          It's about: <%= todo_list.title.humanize %>
        </div>
        <div class="panel-body" style="padding: 30px">
          <div class="row">
            <div class="col-md-4">
              <ul>
                <%= link_to 'Items', todo_list_items_path(todo_list) %> |

      <%= link_to 'Show', todo_list %>
              </ul>
            </div>
            <div class="col-md-4">
              <ul>
                <%= link_to edit_todo_list_path(todo_list) do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>
                <%= link_to todo_list_path(todo_list), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <i class="btn btn-success"><%= link_to 'New Todo list', new_todo_list_path %></i>
  </div>
</div>

app/views/todo_lists/new.html.erb
<h3>New Todo List</h3>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h1><%= @todo_list.title %></h1>

  
<% if @todo_list.is_incomplete_items? %>
<h3>Incomplete Items:</h3>

<ul>
	<% @todo_list.items.incomplete.each do |item| %>
	<li><%= item.content %></li>
	<% end %>
</ul>
<% end %>


<% if @todo_list.is_complete_items? %>
<h3>complete Items:</h3>

<ul>
	<% @todo_list.items.complete.each do |item| %>
	<li><%= item.content %></li>
	<% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>