config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :new]
  resources :welcome, only: [:index]
  resources :todo_lists do
    resources :items do
      member do
        patch :complete
      end
    end
  end

  resources :photos
  resources :password_resets, only: [:new, :create,:edit, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :todo_list
  has_many :photos, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :address_changed?


  validates :content, presence: true,
    length: { minimum: 2 }


  scope :incomplete, -> { where(completed_at: nil) }
  scope :complete, -> { where("completed_at is not null") }



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user
  before_action :find_todolist_id

  def index
    @items = current_user.todo_lists(@items)

  end

  def show
    @photos = @item.photos
  end

  def new
    @item = @todo_list.items.new
  end

  def edit
    @item = @todo_list.items.find(params[:id])

    if current_user.id = @item.id

      @photos = @item.photos
    else
      redirect_to root_path, notice: "You don't have permission!"
    end
  end


  def create
    @item = @todo_list.items.new(item_params)
    # byebug
    if @item.save
      # byebug
      if params[:images]
        params[:images].each do |image|
          @item.photos.create(image: image)
          # byebug
        end
      end

      photos = @item.photos
      flash[:notice] = "new item added!"
      redirect_to '/'
    else
      flash[:info] = "Hey,There is a problem with your adding new item."
      render :new
    end
  end

  def update
    # @item = current_user.items.build(params[:id])
    @item = @todo_list.items.find(params[:id])
    if @item.update_attributes(item_params)
      if params[:images]
        params[:images].each do |image|
          @item.photos.create(image: image)
        end
      end

      flash[:notice] = "item Updated!"
      redirect_to '/'
      # redirect_to todo_list_item(@item)

    else
      flash[:notice] = "Could not Saved!"
      render :edit
    end
  end


  def destroy
    @item = @todo_list.items.find(params[:id])
    if @item.destroy
      flash[:success] = "Item was deleted!"
      # byebug
    else
      flash[:error] = "Item could not be deleted!"
    end
    redirect_to todo_list_items_path
  end

  def complete
    @item = @todo_list.items.find(params[:id])
    @item.update_attribute(:completed_at, Time.now.asctime)
    redirect_to todo_list_items_path, notice: "It's done!"
  end
end

private

def find_todolist_id
  # scope problem ,checked
  @todo_list = @current_user.todo_lists.find(params[:todo_list_id])

end

def item_params
  params.require(:item).permit(:content, :completed_at, :address, :latitude, :longitude, :todo_list_id)
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for [@todo_list, @item], html: { multipart: true } do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.label :address %>
  <%= form.text_field :address %>
  <%= form.submit "Save" %>

 <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <span class="btn btn-default">
          <i class="glyphicon glyphicon-cloud"></i> Upload Photos
          <%= file_field_tag "images[]", type: :file, multiple: true %>
        </span>
      </div>
    </div>
  </div>
  <div id="photos"><%= render 'photos/list' %></div>


  <!-- google map  -->

<div class="row">
  <div class="col-md-12">
     <div id="map"></div>

       <style>
      #map {
        width: 100%;
        height: 400px;
        background-color: grey;
      }
    </style>

     <script>
      function initMap() {
        var uluru = {lat: <%= @item.latitude %>, lng: <%= @item.longitude %> };
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwwTV3QbTUY6O0UHuXCMf4Lh-nHnf4X1o&callback=initMap">
    </script>

  </div>
</div>

<% end %>

app/views/items/edit.html.erb
<h3> Edit: </h3>
<h4><%= @todo_list.title %> </h4>
<%= render 'form' %>

app/views/items/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= @todo_list.title %></div>
  <div class="panel-body">
    <% @todo_list.items.each do |item| %>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p><%= item.content %></p>
            <% if !item.completed_at.blank? %>
              <%= item.completed_at %>
            <% else %>
              <i class="btn btn-default"><%= link_to "Mark Complete", complete_todo_list_item_path(@todo_list, item), method: :patch %></i>
            <% end %>
            <i class="btn btn-warning"><%= link_to "Edit", edit_todo_list_item_path(@todo_list, item) %></i>
            <i class="btn btn-danger"><%= link_to "Delete", todo_list_item_path(@todo_list, item), method: :delete, data: { confirm: "Are you sure?" } %></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<p>
  <%= link_to "New Item", new_todo_list_item_path, class: "btn btn-primary" %> | 
  <%= link_to "Back", todo_lists_path %>
</p>

app/views/items/new.html.erb
<h3>Add Item</h3>
<h4>Title:</h4>
<h4><%= @todo_list.title %> </h4>
<%= render 'form' %>
 <%= link_to "Back", todo_lists_path %>