config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :new]
  resources :welcome, only: [:index]
  resources :todo_lists do
    resources :items do
      member do
        patch :complete
      end
    end
  end

  resources :photos
  resources :password_resets, only: [:new, :create,:edit, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TickToDo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul>
            <li class="navbar-brand"><%= link_to "TickToDo", '/' %></li>
          </div>
        </ul>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><span class="sr-only"><%= link_to "Todo Lists", todo_lists_path %>(current)</span></</li>
            <ul class="nav navbar-nav">
              <% if logged_in? %>
                <li><%= link_to "All todos", todo_lists_path %></li>
                <li><%= link_to "My Profile", user_path(current_user) %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
                <li class="nav navbar-right"><%= image_tag avatar_url(current_user), class: "img-circle" %>&nbsp;
                    <%= current_user.first_name %></li>
              </li>
            <% else %>
              <li><%= link_to 'Login', '/login' %></li>
              <li><%= link_to 'Signup', '/signup' %></li>
              <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
            </ul>
          <% end %>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </header>
  <body>
    <%= render 'shared/message'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>